package com.smart.domain;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager.mana_id
     *
     * @mbggenerated Sun Jul 20 13:41:04 CST 2014
     */
    private Integer manaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager.mana_name
     *
     * @mbggenerated Sun Jul 20 13:41:04 CST 2014
     */
    private String manaName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager.mana_id
     *
     * @return the value of t_manager.mana_id
     *
     * @mbggenerated Sun Jul 20 13:41:04 CST 2014
     */
    public Integer getManaId() {
        return manaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager.mana_id
     *
     * @param manaId the value for t_manager.mana_id
     *
     * @mbggenerated Sun Jul 20 13:41:04 CST 2014
     */
    public void setManaId(Integer manaId) {
        this.manaId = manaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager.mana_name
     *
     * @return the value of t_manager.mana_name
     *
     * @mbggenerated Sun Jul 20 13:41:04 CST 2014
     */
    public String getManaName() {
        return manaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager.mana_name
     *
     * @param manaName the value for t_manager.mana_name
     *
     * @mbggenerated Sun Jul 20 13:41:04 CST 2014
     */
    public void setManaName(String manaName) {
        this.manaName = manaName;
    }
}